### ISSUE TITLE
Actor data is missing the JSON-LD context for "https://w3id.org/security/v1"

### ISSUE THREAD

**Issue by steve-bate** [xwiki-contrib/application-activitypub#38]
The XWiki AP Actor data is missing the JSON-LD context for "https://w3id.org/security/v1" which defines the terms for publicKey and related data. Mastodon appears to still accept AP documents without that context, but other AP servers may not be so forgiving.

**Comment by manuelleduc** [comment]
https://jira.xwiki.org/browse/XAP-111 created as we don't use Github issues.
